#!/usr/bin/env python3
"""
Analyze manual finreg annotations against detector outputs.

Expected input:
- annotation CSV generated by run_finreg_detector_diagnostic.py and later filled manually
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import statistics
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple


MANUAL_TO_THREE_WAY = {
    "supported": "entailment",
    "unsupported": "neutral",
    "partial": "neutral",
    "ambiguous": "neutral",
    "contradicted": "contradiction",
}


def _to_float(value: Any, default: float = 0.0) -> float:
    try:
        if value is None:
            return default
        return float(value)
    except Exception:
        return default


def _mean(values: Iterable[float]) -> float:
    values = list(values)
    return float(sum(values) / len(values)) if values else 0.0


def _quantile(values: List[float], q: float) -> float:
    if not values:
        return 0.0
    ordered = sorted(values)
    idx = max(0, min(len(ordered) - 1, int(round((len(ordered) - 1) * q))))
    return float(ordered[idx])


def histogram(values: List[float], bins: int = 10) -> Dict[str, Any]:
    counts = [0 for _ in range(bins)]
    for value in values:
        clamped = min(1.0, max(0.0, float(value)))
        idx = min(bins - 1, int(math.floor(clamped * bins)))
        if clamped == 1.0:
            idx = bins - 1
        counts[idx] += 1
    return {
        "bins": bins,
        "counts": counts,
        "min": min(values) if values else 0.0,
        "max": max(values) if values else 0.0,
        "mean": _mean(values),
        "std": float(statistics.pstdev(values)) if len(values) > 1 else 0.0,
        "p05": _quantile(values, 0.05),
        "p50": _quantile(values, 0.50),
        "p95": _quantile(values, 0.95),
    }


def parse_detector_scores(text: str) -> Dict[str, float]:
    scores: Dict[str, float] = {}
    for part in (text or "").split("|"):
        part = part.strip()
        if "=" not in part:
            continue
        key, value = part.split("=", 1)
        scores[key.strip().lower()] = _to_float(value.strip())
    return {
        "entailment_prob_mean": scores.get("e", 0.0),
        "neutral_prob_mean": scores.get("n", 0.0),
        "contradiction_prob_mean": scores.get("c", 0.0),
        "hallucination_prob_topk": scores.get("htopk", 0.0),
        "detector_conflict": scores.get("dconflict", 0.0),
    }


def load_rows(path: Path) -> List[Dict[str, Any]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return [dict(row) for row in csv.DictReader(handle)]


def dominant_detector_label(scores: Dict[str, float]) -> str:
    pairs = [
        ("entailment", _to_float(scores.get("entailment_prob_mean"))),
        ("neutral", _to_float(scores.get("neutral_prob_mean"))),
        ("contradiction", _to_float(scores.get("contradiction_prob_mean"))),
    ]
    return max(pairs, key=lambda item: item[1])[0]


def compute_confusion(
    rows: List[Dict[str, Any]]
) -> Tuple[Dict[str, Dict[str, int]], List[str], List[str]]:
    true_labels = ["entailment", "neutral", "contradiction"]
    pred_labels = ["entailment", "neutral", "contradiction"]
    matrix = {
        true_label: {pred_label: 0 for pred_label in pred_labels}
        for true_label in true_labels
    }
    for row in rows:
        matrix[row["mapped_manual_label"]][row["predicted_detector_label"]] += 1
    return matrix, true_labels, pred_labels


def compute_class_metrics(rows: List[Dict[str, Any]], label: str) -> Dict[str, float]:
    tp = sum(
        1 for row in rows
        if row["mapped_manual_label"] == label and row["predicted_detector_label"] == label
    )
    fp = sum(
        1 for row in rows
        if row["mapped_manual_label"] != label and row["predicted_detector_label"] == label
    )
    fn = sum(
        1 for row in rows
        if row["mapped_manual_label"] == label and row["predicted_detector_label"] != label
    )
    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    f1 = (
        (2.0 * precision * recall) / (precision + recall)
        if (precision + recall) else 0.0
    )
    return {
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "tp": tp,
        "fp": fp,
        "fn": fn,
    }


def error_bucket_rows(rows: List[Dict[str, Any]]) -> Dict[str, List[Dict[str, Any]]]:
    buckets: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for row in rows:
        manual = row["manual_label"]
        pred = row["predicted_detector_label"]
        retrieval_mean = _to_float(row.get("retrieval_mean_score"))
        if manual == "contradicted" and pred == "neutral":
            buckets["contradiction_to_neutral"].append(row)
        if manual == "unsupported" and pred == "entailment":
            buckets["unsupported_to_entailment"].append(row)
        if manual == "partial" and pred == "entailment":
            buckets["partial_to_entailment_collapse"].append(row)
        if manual != "supported" and retrieval_mean < 0.20:
            buckets["retrieval_suspected_errors"].append(row)
        if manual != "supported" and pred == "entailment":
            buckets["detector_suspected_errors"].append(row)
    return buckets


def build_report(
    metrics: Dict[str, Any],
    confusion: Dict[str, Dict[str, int]],
    overlap_stats: Dict[str, Any],
    error_buckets: Dict[str, List[Dict[str, Any]]],
) -> str:
    lines: List[str] = []
    lines.append("# Finreg Manual Annotation Error Analysis")
    lines.append("")
    lines.append("## Core Metrics")
    lines.append("")
    lines.append(f"- Total labeled rows: `{metrics['total']}`")
    lines.append(f"- f1_macro: `{metrics['f1_macro']:.3f}`")
    lines.append(f"- f1_contradiction: `{metrics['f1_contradiction']:.3f}`")
    lines.append(f"- contradiction_recall: `{metrics['contradiction_recall']:.3f}`")
    lines.append(f"- unsupported_recall: `{metrics['unsupported_recall']:.3f}`")
    lines.append(f"- false_positive_rate: `{metrics['false_positive_rate']:.3f}`")
    lines.append("")
    lines.append("## Supported vs Unsupported Overlap")
    lines.append("")
    lines.append(
        f"- Supported contradiction mean: "
        f"`{overlap_stats['supported']['contradiction_prob']['mean']:.3f}`"
    )
    lines.append(
        f"- Unsupported contradiction mean: "
        f"`{overlap_stats['unsupported']['contradiction_prob']['mean']:.3f}`"
    )
    lines.append(
        f"- Overlap flag (p95 supported >= p05 unsupported): "
        f"`{overlap_stats['overlap_flag']}`"
    )
    lines.append("")
    lines.append("## 3-Way Confusion Matrix")
    lines.append("")
    lines.append("| True \\\\ Pred | entailment | neutral | contradiction |")
    lines.append("| --- | ---: | ---: | ---: |")
    for true_label in ("entailment", "neutral", "contradiction"):
        row = confusion[true_label]
        lines.append(
            f"| {true_label} | {row['entailment']} | {row['neutral']} | {row['contradiction']} |"
        )
    lines.append("")
    lines.append("## Error Buckets")
    lines.append("")
    for name, bucket_rows in error_buckets.items():
        lines.append(f"- `{name}`: {len(bucket_rows)}")
    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Analyze manual finreg annotations")
    parser.add_argument(
        "--annotations",
        required=True,
        help="Filled manual_annotation_sheet.csv path",
    )
    parser.add_argument(
        "--output-dir",
        default="evaluation_results/finreg_detector_diagnostic/manual_analysis",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    raw_rows = load_rows(Path(args.annotations))
    rows: List[Dict[str, Any]] = []
    for raw in raw_rows:
        manual_label = (raw.get("label") or "").strip().lower()
        if manual_label not in MANUAL_TO_THREE_WAY:
            continue
        scores = parse_detector_scores(raw.get("detector_scores", ""))
        row = dict(raw)
        row.update(scores)
        row["manual_label"] = manual_label
        row["mapped_manual_label"] = MANUAL_TO_THREE_WAY[manual_label]
        row["predicted_detector_label"] = (
            (raw.get("predicted_detector_label") or "").strip().lower()
            or dominant_detector_label(scores)
        )
        row["retrieval_mean_score"] = _to_float(raw.get("retrieval_mean_score"))
        row["retrieval_max_score"] = _to_float(raw.get("retrieval_max_score"))
        rows.append(row)

    if not rows:
        raise SystemExit("No labeled rows found in annotation file.")

    per_label = {
        label: compute_class_metrics(rows, label)
        for label in ("entailment", "neutral", "contradiction")
    }
    f1_macro = _mean(metrics["f1"] for metrics in per_label.values())

    contradicted_rows = [row for row in rows if row["manual_label"] == "contradicted"]
    unsupported_rows = [row for row in rows if row["manual_label"] == "unsupported"]
    supported_rows = [row for row in rows if row["manual_label"] == "supported"]

    contradiction_recall = (
        sum(1 for row in contradicted_rows if row["predicted_detector_label"] == "contradiction")
        / len(contradicted_rows)
        if contradicted_rows else 0.0
    )
    unsupported_recall = (
        sum(
            1 for row in unsupported_rows
            if row["predicted_detector_label"] in {"neutral", "contradiction"}
        ) / len(unsupported_rows)
        if unsupported_rows else 0.0
    )
    false_positive_rate = (
        sum(
            1 for row in supported_rows
            if row["predicted_detector_label"] in {"neutral", "contradiction"}
        ) / len(supported_rows)
        if supported_rows else 0.0
    )

    confusion, _, _ = compute_confusion(rows)

    supported_contradiction = [_to_float(row["contradiction_prob_mean"]) for row in supported_rows]
    unsupported_contradiction = [_to_float(row["contradiction_prob_mean"]) for row in unsupported_rows]
    overlap_stats = {
        "supported": {"contradiction_prob": histogram(supported_contradiction)},
        "unsupported": {"contradiction_prob": histogram(unsupported_contradiction)},
        "overlap_flag": bool(
            supported_contradiction and unsupported_contradiction
            and _quantile(supported_contradiction, 0.95) >= _quantile(unsupported_contradiction, 0.05)
        ),
    }

    buckets = error_bucket_rows(rows)
    bucket_summary = {
        key: [
            {
                "id": row["id"],
                "question": row["question"],
                "detector_variant": row["detector_variant"],
                "manual_label": row["manual_label"],
                "predicted_detector_label": row["predicted_detector_label"],
                "contradiction_prob_mean": _to_float(row["contradiction_prob_mean"]),
                "entailment_prob_mean": _to_float(row["entailment_prob_mean"]),
                "neutral_prob_mean": _to_float(row["neutral_prob_mean"]),
                "retrieval_mean_score": _to_float(row.get("retrieval_mean_score")),
                "notes": row.get("notes", ""),
            }
            for row in value[:25]
        ]
        for key, value in buckets.items()
    }

    metrics = {
        "total": len(rows),
        "f1_macro": f1_macro,
        "f1_contradiction": per_label["contradiction"]["f1"],
        "contradiction_recall": contradiction_recall,
        "unsupported_recall": unsupported_recall,
        "false_positive_rate": false_positive_rate,
        "per_label": per_label,
    }

    payload = {
        "metrics": metrics,
        "confusion_matrix": confusion,
        "supported_vs_unsupported_overlap": overlap_stats,
        "error_buckets": bucket_summary,
    }
    (output_dir / "manual_label_metrics.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    report = build_report(
        metrics=metrics,
        confusion=confusion,
        overlap_stats=overlap_stats,
        error_buckets=buckets,
    )
    (output_dir / "error_analysis_report.md").write_text(report, encoding="utf-8")
    print(f"Wrote outputs to {output_dir}")
    print(f"- {output_dir / 'manual_label_metrics.json'}")
    print(f"- {output_dir / 'error_analysis_report.md'}")


if __name__ == "__main__":
    main()
